export const FETCH_WEATHER_PENDING = "FEATCH_WEHTER_PENDING";
export const FETCH_CURRENT_SUCCESS = "FEATCH_CURRENT_SUCCESS";

export const FETCH_FORECAST_SUCCESS = "FEATCH_FORECAST_SUCCESS";

export const FETCH_WEATHER_ERROR = "FEATCH_WEHTER_ERROR";

export const SET_CITY = "SET_CITY";
